MVC pattern implementation
danilabokhanov/MaxFlowPresentation pull request #1
Opened 2024-01-17 11:08 UTC by danilabokhanov

Написал MVC, соотвественно Drawer пока ничего не отрисовает. Не уверен, что правильно подключил соединение через сигналы и слоты, т к при нажатии на кнопку "Go Next" получаю Runtime Error (но ошибка может быть в неправильно написанной структуре, пока не дебагал).
Посмотрел твою прошлогоднюю консультации по данному проекту. Правильно понимаю, что предлагается просто раз в условные 50 мс перерисовывать холст полностью для плавной анимации? Просто хочу, чтобы когда поток течёт по ребу, цвет ребра был градиентым и менялся плавно от полностью красного к полностью синему, например. Подходит ли для данной цели qwt?

2024-01-19 17:57 UTC, DimaTrushin requested changes
Обрати внимание, что я вносил комментарии единожды. Во всех похожих ситуациях надо по аналогии исправить то, что я указал в замечаниях.

Из крупного есть некоторые проблемы с логикой обзервера и один плохой конструктор у него, который просто уронит твой код вызовом по нулевому указателю функции.
Другая беда с ним, что ты все делаешь на стороне observer-а. Особенно менеджмент списком подписчиков. Не делай так.
Но самая большая беда с тем, что ты все передаешь по указателю. Во-первых, уж лучше по ссылке чтобы не бодаться с нулевыми указателями. А во-вторых, метод draw в Qt не блокирующий. Потому ты не можешь просто так передать данные не by value. Если ты их передашь по ссылке или по указателю, то пока дойдет очередь до обработки сообщения там вечность пройдет и твои данные просто помрут, переедут или умрут. Так делать не стоти вообще никогда. Потому в тот момент как ты оповещаешь observera надо заворачивать все в shared_ptr<const T> и передавать by value. Это стандартная ситуация как перейти к value semantics дешево. Если так не сделать это потенциальное нарушение всех инвариантов.

Я бы еще немного структурировал файлы разбив по папочкам что относится к ядру, что к графике, что к библиотечному коду, что к общему коду приложения.

Еще отключи exception. В Qt event loop их все равно кидать запрещено, он не безопасен для этого. Правильно писать обработку исключений в Qt event loop это нетривиальная задача. Проще их отключить. НО писать надо код так, как будто exception есть.

Кидать exception в тех местах где ты кидаешь глупо. Там либо инвариант класса и условие обязано гарантироваться классом. Либо ошибка программиста. И то и другое проверяется assert-ом.

Есть еще куча мелких вещей, все указано в комментариях.

2024-01-19 17:57 UTC, DimaTrushin commented on MaxFlowAlgorithmPresentaion.pro
> +include($${OUT_PWD}/conanbuildinfo.pri)
Тебе стоит добавить readme с описанием шагов по сборке проекта, потому что тут либо надо вызывать conan до сборки, либо добавить в шаги сборки в ide команду для конана.

2024-01-19 17:57 UTC, DimaTrushin commented on MaxFlowAlgorithmPresentaion.pro
Я бы немного откорректировал структуру проекта папками. Например сделал бы папку Kenel и папку Interface для того, чтобы весь код релевантный для ядра программы поместить в Kernel, а для GUI и интерфейса в Interface. А общие вещи вроде application, main и файлы настройки снаружи в корне.

2024-01-19 17:57 UTC, DimaTrushin commented on MaxFlowAlgorithmPresentaion.pro.user
Это машино зависимый файл. Его не должно быть в проекте. Потому что это настройки именно твоей машины. Тут содержится информация о kit-ах и прочей хрени, что у других пользователей будет другим. Убрать.

2024-01-19 17:57 UTC, DimaTrushin commented on main.cpp
> +    max_flow_app::Application app;
Рекомендую либо выключить исключения в проекте полностью (но писать как будто они есть), либо как-то предусмотреть перехват исключений в Qt EventLoop. Спойлер -- это супер нетривиально.

2024-01-19 17:57 UTC, DimaTrushin commented on application.cpp
> +Application::Application(): model_(), view_(),
Конструкторы по умолчанию можно не указывать. Они и так вызовутся.

2024-01-19 17:57 UTC, DimaTrushin commented on mainwindow.cpp
> +MainWindow::~MainWindow() {
Сделай
```cpp
MainWindow::~MainWindow() = default;
```

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +    }
Очень плохо. Если тебе передадут rvalue ссылку, то у тебя notify_fun и unsubscribe_func будут пустыми. Потому что при первом вызове ты мувнишь данные в subscribe_func. Тут нет никакого способа кроме как передавать по константной ссылке данные или же кастовать std::forward только в unsubscribe_func.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +    std::function<void(DataPtr)> subscribe_func_ = DefaultOnCallFunc,
Не определяй через запятую однотипные данные. Как ты видишь экономии в строчках у тебя все равно не будет, а читаемость повысится. Вообще возможность объявлять за раз 100500 данных это не фича C++, а необходимость для обратной совместимости с Си.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +        std::function<DataPtr()>* data_producer_ptr;
Почему указатель на std::function? Почему не просто std::function? Выглядит так как ты выкинул кишки из инкапсюляции.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +        OnUnsubscribe((*connection_.data_producer_ptr)());
Я в этом месте предпочитаю делать так. Мы вместо того, чтобы хранить источник информации просим у observable, чтобы она нас отписала и сообщаем ей свой адрес (для этого дергаем ее приватный метод). И вот она уже сама передаст данные. Это избавляет observer от необходимости беспокоиться об источнике данных, который он не должен уметь дергать. Он вообще может быть не валидным в момент, когда observer его дернет.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +    std::function<typename Observer<DataType>::DataPtr()> data_producer_;
1) Заведи нормальный юзинг.
2) Когда тебе приходится явно писать typename и ты не определяешь using, ты делаешь что-то не так.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +            throw std::runtime_error("empty data producer");
Это глупость. Это условие инвариант класса. Ты должен гарантировать, что у тебя в data_producer_ лежит не пустой метод.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +            throw std::runtime_error("null pointer to subscriber");
Не уверен, что хорошая идея падать с exception особенно в Qt коде. Я бы тут поставил либо assert либо return (если ты не считаешь это ошибкой). Просто если ты считаешь нулевой указатель тут ошибкой, то это ошибка программиста и надо исправлять код. А в этом случае надо ставить assert.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +        data_producer_();
А это нахрена тут!?

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +    void OnSubscribe(DataPtr data) {
Я только сейчас заметил. Какого хрена у тебя данные по указателю путешествуют!? Ты нарушаешь всю value semantics одним махом. Передавай тогда хотя бы по константной ссылке. А так ты можешь кишки вспороть любому классу. Либо сделай шаблонный параметр как передавать данные по ссылке или по значению.
Я хочу сказать, что тебе все равно понадобится обзервер который принимает данные by value, потому что в Qt метод draw не блокирующий и у тебя нет гарантий, что у тебя данные не умрут за то время пока event loop дойдет до обработки сообщения по отрисовке. Это очень опасная игра.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +    bool IsConnected() {
Почему не константный метод? Сделать константным.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +    void OnSubscribe(DataPtr data) {
Все методы реагирования должны быть константными.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +        for (auto& ptr : subscribers_) {
Не надо писать ссылку перед указателем. Это лишний jump ненужный. Просто auto ptr. Надо понимать что дорого, а что нет. Указатели это дешево by value, но дорого by reference и by pointer.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +            subscribers_.back()->Unsubscribe();
Плохая тема просить пользователя отписать от себя. Тогда пользователь менеджерит твой контейнер subscribers_. Ты уверен, что у тебя не инвалидируется состояние контейнера когда ты такую хуйню делаешь? Перенеси логику менеджмента списка в observable.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
> +            throw std::runtime_error("empty data producer");
Это инвариант класса.

2024-01-19 17:57 UTC, DimaTrushin commented on observer_pattern.h
Тебе надо обязательно обеспечить возможность передавать данные по значению для неблокирующих вызовов. Данные будешь скалывать в shared_ptr<const T> чтобы копирования были дешовыми.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.h
> +
Зачем столько вертикальных пробелов? Убрать.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.h
> +    void SetVertexStatus(size_t vertex, const Status& status, bool should_notify);
enum class передавай by value.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.h
> +    bool is_path_processed_successfully_ = false;
Выглядит по названию не как переменная для класса, а как переменная для метода, который обрабатывает путь. А если она не имеет смысла между вызовами метода, то не должна храниться в объекте.
Проверь все остальные данные ты точно должен эту информацию хранить между вызовами. Подумай, что они должны описывать именно состояние объекта, а не состояние какого-то метода объекта.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.h
> +    MaxFlow();
Раз у тебя есть дефолтные значения, ты можешь написать MaxFlow() = default; Тебе лишь надо обзерверу тоже присвоить дефолтное значение. Можешь создать для этого метод.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.cpp
> +    data_.vertices_.resize(n, Status::Basic);
Что мешало в конструкторе задать data_ с помощью aggregate initialization?

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.cpp
> +    data_.edges_.push_back({.u = edge.to, .to = edge.u, .delta = 0});
Вообще мне всегда не нравилось, когда надо писать код вида obj.subobj.method(). Это значит что у тебя не правильно настроены границы доступа к данным. Объект не обладает нужными навыками общения, чтобы коммуницировать с внешним миром и ты открываешь его кишки. Я бы сделал вот как. Я бы ребра и вершины хранил бы отдельно двумя векторами, а в Data я бы положил std::reference_wrapper вместо самих векторов. И тогда Data можно будет дешево передавать by value.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.cpp
> +    while (!queue.empty()) {
Вот скажи мне, я прав или нет. Такое ощущение, что у тебя есть некоторая работа, которую ты делаешь пока у тебя очередь не пуста. А раз так, то я бы ожидал тут что-то вроде
```cpp
while (!queue.empty()) {
  do_some_work1(...);
  do_some_wokr2(...);
}
```
При этом я бы явно передавал все параметры, чтобы было видно как текут данные, чтобы за этим можно было уследить.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.cpp
> +        }
Вот это выглядит как подметод с определенной работой.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.cpp
> +    SetVertexStatus(0, Status::OnTheNetwork, true);
Вот тут у тебя ошибка уровня абстракции. Строчки с 97 по 102 делают низкоуровневую работу и потом внезапно вызывается высокоуровневая функция SetVertexStatus. Тебе надо получше подумать над рефактором этого кода.

2024-01-19 17:57 UTC, DimaTrushin commented on max_flow.h
> +    observer_pattern::Subject<Data> graph_ovservable_;
Пиши корректно observable, а то невозможно даже найти твою переменную.

2024-01-19 17:57 UTC, DimaTrushin commented on controller.h
> +    void CallGoNext();
По хорошему у контроллера вообще не должно быть ничего в интерфейсе кроме конструктора и порта для подписи. Зачем все эти методы? Если они дергаются снаружи, то это ошибка дизайна. Если они дергаются изнутри, то почему они не приватные?

2024-01-19 17:57 UTC, DimaTrushin commented on controller.cpp
> +      view_observer_([] (const View::ViewSendingData*){},
Вместо такой простыни сделай метод приватный handle_data(...) с нужной сигнатурой и перехватывай this в одной лямбде и вызывай метод handle_data.

2024-01-19 17:57 UTC, DimaTrushin commented on controller.cpp
> +          if (data ->signal_type == View::ViewSendingData::CHANGE_VERTICES_NUMBER) {
Сделай нормальный switch

2024-01-19 17:57 UTC, DimaTrushin commented on view.h
> +    Q_OBJECT
Кстати, как вариант можно еще контроллер напрямую подписывать на события из Qt объектов. Но я не знаю, как тут будет лучше. Это так для заметки.

2024-01-19 17:57 UTC, DimaTrushin commented on view.h
> +    using GraphObserver = observer_pattern::Observer<MaxFlow::Data>;
Чтобы максимально развести observer и observable можно делать отдельный header где находится тип передаваемых данных. Тогда view вообще не будет знать header для model.

2024-01-19 17:57 UTC, DimaTrushin commented on view.h
> +    void UpdateGraphView(const MaxFlow::Data* data);
Зачем этот метод в публичном интерфейсе? Я бы ожидал что все действия происходят только по событиям которые обрабатываются соответствующими обработчиками. Так что я бы скрыл все лишнее.

2024-01-19 17:57 UTC, DimaTrushin commented on view.h
> +    ViewObservable view_observable_;
Это скорее CommandObservable, потому что из него прилетают команды на управление моделью.

2024-01-19 17:57 UTC, DimaTrushin commented on view.cpp
> +            SLOT (ApplyButtonPressed()));
Сейчас есть более новый синтаксис вызова через указатели на функции. Он более предпочтительный.

2024-01-19 17:57 UTC, DimaTrushin commented on view.cpp
> +    message_.args = static_cast<size_t>(spin_box -> value());
Чтобы избежать кастов можно было сделать разные observable под каждый вид сигналов. Но это не обязательно.

2024-01-24 20:30 UTC, danilabokhanov commented on max_flow.h
> +    MaxFlow();
Сделал так, только почему-то дефолтный конструктор могу написать только в cpp файле, в хедере не даёт определить

2024-01-24 20:34 UTC, danilabokhanov commented on max_flow.cpp
> +    data_.edges_.push_back({.u = edge.to, .to = edge.u, .delta = 0});
только в ref_wrapper оборачивать наверное нельзя, т к обработка нажатия по кнопке в qt не блокирующая, поэтому через этот ref_wrapper можно увидеть просроченные данные, во всём остальном согласен.

2024-01-25 14:58 UTC, danilabokhanov commented on observer_pattern.h
Исправил, вроде теперь нормально должно работать: нам важно только то, чтобы data_producer возвращал данные по значению, все остальные
```

2024-01-25 15:17 UTC, danilabokhanov commented on observer_pattern.h
Если всё правильно понял, то shared_ptr не нужен. Сделал так, чтобы data_producer возвращал данные по значению, а все остальные лямбды сделал по константной ссылке. Когда вызывается Notify, то в нём создаётся копия текущих данных в переменной data, а уже во все лямбды она по ссылке рассылается. Соответсвенно пока скоуп Notify жив, то жива и переменная data, а значит лябды корректно могут обращаться по ссылке к этой data
```

2024-03-22 13:50 UTC, DimaTrushin requested changes
Выглядит очень прилично. Я добавил пару замечаний связанных с Qt ресурсами и потенциальным двойным удалением памяти. И еще я тебе сделал медвежью услугу с обзервером. Так как у тебя он блокирующий нет смысла передавать не по ссылке. Так что у тебя сейчас там несколько лишних копирований происходит, которые можно убрать. data_producer_ можно сделать так, чтобы возвращал константную ссылку и все будет норм работать, потому что в qt ты все равно данные все копируешь, а значит при передаче между портами можно не париться и не копировать ничего.

2024-03-22 13:50 UTC, DimaTrushin commented on Interface/drawer.h
> +                                                                {Status::OnThePath, {102, 0, 0}}};
Когда такое большое количество констант, то полезно делать вспомогательный класс Palette (палитра) и в нем хранить все настроки. И для этого класса иметь дефолтную инициализацию. А саму палитру хранить как еще одну переменную. В больших проектах, эту палитру можно сообщать так же через observer pattern.

2024-03-22 13:50 UTC, DimaTrushin commented on Interface/drawer.h
> +
У тебя переменные класса раскиданы по всему классу. Сгруппируй их все в конце класса. Иначе их очень тяжело искать и ты никогда не уверен, все ли ты видел данные в классе или надо еще где-то порыться.

2024-03-22 13:50 UTC, DimaTrushin commented on Interface/drawer.h
> +    std::unique_ptr<QwtPlot> plot_;
Ты потом в конструкторе пишешь
```cpp
plot_(new QwtPlot(frame))
```
Когда ты Qt объекту сообщаешь в конструкторе родителя, то родитель начинает владеть Qt объектом. А с другой стороны, тут у тебя unique_ptr. А потому у тебя произойдет двойное удаление памяти, когда у тебя вызовется деструктор frame. Так лучше не делать. Надо либо не давать родителя Qt объекту и тогда его хранить в unique_ptr, либо давать, но в этом случае надо хранить обычный указатель, который будет просто ссылаться на этот Qt объект. Второй способ часто предпочтительнее, потому что бывают ситуации, когда ты не можешь не дать родителя.

2024-03-22 13:50 UTC, DimaTrushin commented on Interface/drawer.h
> +        std::unique_ptr<QwtPlotCurve> base;
Оборачивая так данные в unique_ptr-ы обрати внимание на то, что QwtPlot удаляет по умолчанию данные при вызове detachItems. А значит если эти данные хранятся в unique_ptr, то это потенциальное двойное удаление памяти. Но при этом надо иметь в виду, что деструктор QwtPlot НЕ удаляет присоединенные items. И это просто фейл дизайна. Надо дополнительно вызвать setAutoDelete(true).

2024-03-22 13:50 UTC, DimaTrushin commented on Interface/drawer.cpp
> +                        -M_PI / (number / 2) * (index + 1) / 2, kMaxX * (0.5 - kSinkPadingRate));
Вместо M_PI есть std::numbers::pi. Если ты пользуешься c++20. Хотя он вроде имеет меньше знаков по умолчанию, чем M_PI.

2024-03-22 13:50 UTC, DimaTrushin commented on Interface/drawer.cpp
> +    return kEdgeColor.at(edge.status);
А почему at? Ты точно хочешь кидать исключения на доступе? Если да, то ты точно ловишь их где надо, чтобы они не улетали в qt event loop?

2024-03-22 13:50 UTC, DimaTrushin commented on Interface/drawer.cpp
> +    plot_ -> setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
Не консистентные пробелы. У тебя везде ниже -> идет без пробелов слева и справа, а тут везде пробелы. Судя по всему clang-format не применялся к этому файлу.

2024-03-22 13:50 UTC, DimaTrushin commented on Interface/drawer.cpp
> +    edge.tail.reset(new QwtPlotCurve());
Елси ты кладешь указатель в unique_ptr, то лучше пиши std::make_unique, чтобы читатель этого кода об этом знал. Дело в том, что иначе мне надо искать определение tail внутри edge, чтобы быть уверенным, что тут объект без родителя внезапно не оказался в нехолдящем указателе.

2024-03-22 13:50 UTC, DimaTrushin commented on observer_pattern.h
Можно еще лучше сделать. Так как у тебя блокирующие вызовы, то data_producer_ может возвращать константную ссылку на объект и ты ее тут же передаешь в onNotify. Мой комментарий был не совсем релевантен, потому что ты в Qt данные и так передаешь by value. Я еще раз на всякий случай прокомментирую это в observer_pattern.h.

2024-03-22 13:50 UTC, DimaTrushin commented on Library/observer_pattern.h
> +    }
Так как у тебя блокирующий observer, то мой комментарий был не очень релевантным. Ты в qt данные и так по копии передаешь. А вот тут копию делать не обязательно. Потому можно просто возвращать по константной ссылке. Ты же все равно принимаешь по константной ссылке в observer-е.

2024-03-22 13:50 UTC, DimaTrushin commented on Library/observer_pattern.h
> +    }
Я бы еще добавил везде assert-ов, что нам случайно сюда nullptr-ы не скормили и все методы живые.

2024-03-22 13:50 UTC, DimaTrushin commented on Library/observer_pattern.h
> +    static void DefaultOnCallFunc(DataType) {
Принимай тут по ссылке. Потому что иначе тут просто делается ненужная копия. Ты и так везде по ссылке принимаешь.

2024-03-22 13:50 UTC, DimaTrushin commented on Library/observer_pattern.h
> +    void Subscribe(SubscriberPtr consumer) {
Что если comsumer уже был подписан? Тогда ты сломал инвариант observable, к которому он был подписан. Надо проверить, что он не подписан и если подписан, то решить как мы будем поступать, либо насильственно отписывать, либо же возвращать вместо void статус операции о том, подписался ли он или нет.

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/view.h
> +    SendingData message_;
1) Не делай публичные данные с _ в конце имени.
2) Почему вообще в классе у тебя есть публичное данное!? Ты не нарушаешь ли этим инвариант класса?

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/view.h
> +public slots:
А точно слоты должны быть публичные? Ты разрешаешь кому-то снаружи их позвать? Или только присоединиться к ним можно?

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/view.h
> +    using BasicEdge = mvc_messages::BasicEdge;
1) Все ли эти данные должны быть публичными?
2) У тебя перемешаны методы и типы (юзинги). Сначала конструктор, потом юзинги типов, потом метод, потом переменная класса, потом опять методы. Надо навести порядок.

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/view.cpp
> +      main_window_(),
Дефолтный конструктор можно явно не вызывать. Он и так вызовется.

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/view.cpp
> +    message_.args = static_cast<size_t>(spin_box -> value());
Если совсем придираться, то тут не хватает метода value(spin_box), который внутри себя делает этот каст.

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/view.cpp
> +View::SendingData View::ProduceViewMessage() const {
А ты точно хочешь by value это передавать?

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/mvc_messages.h
> +        CHANGE_VERTICES_NUMBER,
Используй ONLY_CAPS стиль только для макрасов! Это сбивает разработчиков с толку, когда ты такое пишешь для enum-ов.
Я правильно понимаю, что ты хочешь использовать enum как флаг с операторами | и &? Если нет, то почему НЕ enum class?

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/max_flow.h
> +    Data GetData() const;
Почему этот метод публичный? Это же деталь имплементации, которая нужна лишь для порта оповещения. А к порту достаточно подписаться.
И да, повторюсь еще раз, что я подвел тебя и дал не верные указания по поводу того, как надо возвращать данные. В блокирующем обзервере лучше по константной ссылке, особенно если данные тяжелые.

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/max_flow.cpp
> +MaxFlow::MaxFlow(size_t n, size_t m, const std::vector<BasicEdge> &edges)
Не лушая идея в конструкторе писать конкретные контейнеры. Если у тебя будет другой контейнер, который можно кастануть к вектору неявно (например std::initializer_list<BasicEdge>), то у тебя тут создастся временный контейнер и потом он удалится после вызова конструктора. Это может быть потенциально дорого. Потому либо принимай std::initializer_list, либо принимай итераторы, либо лучше принять rvalue reference на вектор, тогда его внутренности можно украсть (если это тебе нужно).

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/max_flow.cpp
> +void MaxFlow::ExtendNetwork(size_t vertex, std::vector<bool>& used,
В целом мне не нравится такой стиль, когда ты передаешь аргументы по неконстантной ссылке (я предпочитаю их передавать по указателю, чтобы было видно, что аргумент изменится, как в scanf), но думаю, что тут можно так оставить. Все более или менее гармонично читается. Просто замечание на будущее.

2024-03-22 13:50 UTC, DimaTrushin commented on Kernel/controller.cpp
> +            CallGoNext();
Я бы в кейсах перебрал все значения констант, а в дефолте бы поставил assert(false), чтобы в будущем не забыть добавить новый случай, если вдруг он понадобится.

2024-04-25 11:41 UTC, merged

2024-05-20 09:28 UTC, DimaTrushin reviewed
Сделал несколько минорных замечаний.

2024-05-20 09:28 UTC, DimaTrushin commented on MaxFlowAlgorithmPresentaion.pro
> +QMAKE_CXXFLAGS += -std=c++20
Лучше не писать компиляторо зависимых флагов. Тем более, что ниже ты в CONFIG добавил флаг c++20.

2024-05-20 09:28 UTC, DimaTrushin commented on MaxFlowAlgorithmPresentaion.pro
Не вижу где отключены исключения.

2024-05-20 09:28 UTC, DimaTrushin commented on Library/observer_pattern.h
> +        for (auto subscriber_ptr : subscribers_) {
есть же стандартные алгоритмы проверки принадлежности контейнеру.

2024-05-20 09:28 UTC, DimaTrushin commented on Library/observer_pattern.h
> +    const DataType& GetData() {
Очень плохо. У тебя data_producer_ возвращает данные по значению (то есть это временный локальный объект), а потом ты его возвращаешь по константной ссылке. Так как у тебя блокирующий обзервер лучше сделай data_producer_ типа std::function<const DataType&()>; Тогда эта проблема исчезнет. У тебя кто-то другой будет владеть этими данными.

2024-05-20 09:28 UTC, DimaTrushin commented on Library/observer_pattern.h
> +    const DataType& GetData() {
Почему метод НЕ константный?

2024-05-20 09:28 UTC, DimaTrushin commented on Library/observer_pattern.h
> +        DataType data = data_producer_();
Вот тут тоже нет смысла делать временный объект. Перейди везде на ссылки.

2024-05-20 09:28 UTC, DimaTrushin commented on Library/observer_pattern.h
> +        consumer->OnSubscribe(std::move(data_producer_()));
Тут не нужен move. У тебя OnSubscribe не поддерживает move и data_producer_ уже возвращает rvalue.

2024-05-20 09:28 UTC, DimaTrushin commented on Kernel/max_flow.h
> +    void RegisterNetworkObserver(observer_pattern::Observer<Data>* observer);
Заводи юзинги в начале класса, чтобы не писать длинные квалификаторы доступа.

2024-05-20 09:28 UTC, DimaTrushin commented on Kernel/max_flow.h
> +    size_t FindEdge(const MaxFlow::BasicEdge& edge);
внутри класса не надо использовать квалификатор доступа к классу.

2024-05-20 09:28 UTC, DimaTrushin commented on Kernel/max_flow.h
> +        std::vector<BasicEdge> edges;
На эти данные вообще нет инвариантов?

2024-05-20 09:28 UTC, DimaTrushin commented on Kernel/max_flow.h
> +    inline static const size_t kMinVerticesNum = 2, kMaxVerticesNum = 10, kMaxEdgeCapacity = 100,
убери inline (так как все переменные статические внутри класса идут inline. И еще сделай constexpr. И НЕ объявляй несколько переменных в одной строчке. Это читать не возможно.

2024-05-20 09:28 UTC, DimaTrushin commented on Interface/drawer.cpp
> +    edge.tail = new QwtPlotCurve();
Ну как так.